name: CI Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - developments
      - feature

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout COde
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/actions-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          version: "20"
          cache: "pnpm"

      - name: Install dependencies
        uses: pnpm isntall --frozen-lockfile

      - name: Test
        uses: pnpm test

      - name: Build
        uses: pnpm build
